version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-container
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"

  frontend:
    build:
      context: ./ui  # Correct path to the ui directory
      dockerfile: Dockerfile  # Assumes Dockerfile is inside ui/
    container_name: frontend-container
    volumes:
      - ./ui:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/var/www/html
      - ./ui/build:/var/www/html/frontend
    depends_on:
      - php
      - frontend

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
