version: '3.8'

services:
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php-container
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_NAME=shop_db
      - DB_USER=sanusi
      - DB_PASS=password
    command: php -S 0.0.0.0:9000 -t public

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: frontend-container
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:9000
    command: npm start

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: pa$$word
      MYSQL_DATABASE: shop_db
      MYSQL_USER: sanusi
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: